version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8.9-browsers
    working_directory: ~/repo
    
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install
      - run: sudo npm install -g @angular/cli

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: echo test #ng test
      - persist_to_workspace:
            root: ~/repo
            paths:
              - .
  deploy:  
    docker:
     - image: circleci/node:8.9
    working_directory: ~/repo
    steps:
      - checkout 
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
         at: .
      # deploy!
      - run: npm run deploy-storybook -- --ci --host-token-env-variable=${GITHUB_TOKEN}

        
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - deploy:
         requires:
          - test
         filters:
            branches:
              only:
                - master 
          

