version: 2
jobs:
  test:
    docker:
      - image: circleci/node:11.4-browsers
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
           key: bob-style-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: bob-style-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      # run tests!
       #npm run to run ng because @angular/cli is not installed globally.

      - run: npm run test -- --watch=false --progress=false --browsers=ChromeHeadless
      - run: npm run build-storybook
      - store_test_results:
          path: ~/repo/test-results/
      - store_artifacts:
          path: ~/repo/test-results/
      - persist_to_workspace:
            root: ~/repo
            paths:
              - .
  deploy:
    docker:
     - image: circleci/node:11.4
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
         at: .
      # deploy!
      - run: mkdir -p .out/.circleci && cp -a .circleci/. .out/.circleci/.
      - run: npm run build-storybook
      - run: npm run deploy-storybook --  --existing-output-dir=.out --ci --host-token-env-variable=${GITHUB_TOKEN}



workflows:
  version: 2
  build_and_test:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - gh-pages
      - deploy:
         requires:
          - test
         filters:
            branches:
              only:
                - master


